### ISSUE TITLE
Vegan Caramel

### ISSUE THREAD

**Issue by stevenpollack** [darpacakefoundation/notes#23]
Adapted from [this](http://minimalistbaker.com/4-ingredient-bourbon-caramel-sauce/):

Ingredients:

- 200g sugar
- 60g water
- 125g full fat coconut milk
- pinch of salt

Directions:
- Simmer sugar and water on medium heat, swirling pan NOT stirring for about 15 minutes or until a deep amber color is reached. Watch closely as not to let it burn.
- Turn off burner and remove from heat and slowly add cream while stirring.
- Add pinch of salt and place back on still-warm burner for another minute while stirring.
- Transfer to a heat-safe dish or bottle and let cool. Store covered in the refrigerator and bring to room temp or heat in a warm water bath before serving. You can also just simply microwave the jar for 30 seconds before each use without affecting the texture or flavor.

**Comment by stevenpollack** [comment]
Note: I'm pretty sure I fucked this up:

- when I took the thing off medium heat (once at deep amber), I started pouring in the coconut milk and noticed the entire mixture was pretty seized up and needed three hands to pour, and stir.
- hand to put it back on heat to make sure the milk and caramel properly integrated, and even then, it came out pretty watery afterwards with a small crust of caramel stuck to the sides.

**Comment by stevenpollack** [comment]
@davidazaria do you have any suggestions for this? I was thinking of just something simple to throw on brownies...

**Comment by davidazaria** [comment]
@stevenpollack What do you mean by "throw on" brownies -- like a topping of some sort?

**Comment by stevenpollack** [comment]
Precisely. I'm also thinking about doing some sort of coffee glaze (i.e. powdered sugar + coffee)...

**Comment by davidazaria** [comment]
If you're looking for brownie toppings, I always think sea salt (you can infuse it w/ a type of herb like rosemary, too) is an excellent addition.

**Comment by stevenpollack** [comment]
http://avirtualvegan.com/five-minute-vegan-caramel-sauce/
