### ISSUE TITLE
Vegan nutella

### ISSUE THREAD

**Issue by stevenpollack** [darpacakefoundation/notes#3]
Leads:
- look into Gianduja (poor man's nutella)
- [Gianduja filling for chocolates](http://www.chefeddy.com/2009/12/belgian-chocolates/)
- [hazelnut spread](http://www.food.com/recipe/gianduia-gianduja-nutella-chocolate-hazelnut-spread-367139)

**Comment by jonathanepollack** [comment]
v5.5

### Ingredients
* 200 g Hazelnuts
* 15 g Cocoa Butter
* 15 g Cocoa Powder
* 6 g Saccharin

### Results

Good consistency, but could be made more solid, and 'wetter' via some addition of fat.

**Comment by jonathanepollack** [comment]
v6.0

### Ingredients
* 200 g Hazelnuts
* 15 g Cocoa Butter
* 15 g Cocoa Powder
* 20 g Coconut Oil
* 6 g Saccharin

### Results

Not solid enough, and still too dry.

**Comment by jonathanepollack** [comment]
v6.1

### Ingredients
* 200 g Hazelnuts
* 20 g Cocoa Butter
* 20 g Cocoa Powder
* 50 g Coconut Oil
* 6 g Saccharin

### Results

Way too runny. Was finally appropriately "wet", however. Definitely work on trading between Cocoa Butter and Coconut Oil (to make more solid) -- perhaps up Cocoa Powder to dry things up _a little_.
